// Mocks generated by Mockito 5.0.15 from annotations
// in solevato_client_sdk_flutter/test/data/local/local_storage_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:solevato_client_sdk_flutter/data/local/dao/solevato_contact_dao.dart'
    as _i5;
import 'package:solevato_client_sdk_flutter/data/local/dao/solevato_conversation_dao.dart'
    as _i2;
import 'package:solevato_client_sdk_flutter/data/local/dao/solevato_messages_dao.dart'
    as _i7;
import 'package:solevato_client_sdk_flutter/data/local/dao/solevato_user_dao.dart'
    as _i9;
import 'package:solevato_client_sdk_flutter/data/local/entity/solevato_contact.dart'
    as _i6;
import 'package:solevato_client_sdk_flutter/data/local/entity/solevato_conversation.dart'
    as _i4;
import 'package:solevato_client_sdk_flutter/data/local/entity/solevato_message.dart'
    as _i8;
import 'package:solevato_client_sdk_flutter/data/local/entity/solevato_user.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [SolevatoConversationDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSolevatoConversationDao extends _i1.Mock
    implements _i2.SolevatoConversationDao {
  MockSolevatoConversationDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveConversation(_i4.SolevatoConversation? conversation) =>
      (super.noSuchMethod(Invocation.method(#saveConversation, [conversation]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteConversation() =>
      (super.noSuchMethod(Invocation.method(#deleteConversation, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> onDispose() =>
      (super.noSuchMethod(Invocation.method(#onDispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SolevatoContactDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSolevatoContactDao extends _i1.Mock
    implements _i5.SolevatoContactDao {
  MockSolevatoContactDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveContact(_i6.SolevatoContact? contact) =>
      (super.noSuchMethod(Invocation.method(#saveContact, [contact]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteContact() =>
      (super.noSuchMethod(Invocation.method(#deleteContact, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> onDispose() =>
      (super.noSuchMethod(Invocation.method(#onDispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SolevatoMessagesDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSolevatoMessagesDao extends _i1.Mock
    implements _i7.SolevatoMessagesDao {
  MockSolevatoMessagesDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveMessage(_i8.SolevatoMessage? message) =>
      (super.noSuchMethod(Invocation.method(#saveMessage, [message]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> saveAllMessages(List<_i8.SolevatoMessage>? messages) =>
      (super.noSuchMethod(Invocation.method(#saveAllMessages, [messages]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i8.SolevatoMessage? getMessage(int? messageId) =>
      (super.noSuchMethod(Invocation.method(#getMessage, [messageId]))
          as _i8.SolevatoMessage?);
  @override
  List<_i8.SolevatoMessage> getMessages() =>
      (super.noSuchMethod(Invocation.method(#getMessages, []),
          returnValue: <_i8.SolevatoMessage>[]) as List<_i8.SolevatoMessage>);
  @override
  _i3.Future<void> clear() => (super.noSuchMethod(Invocation.method(#clear, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteMessage(int? messageId) =>
      (super.noSuchMethod(Invocation.method(#deleteMessage, [messageId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> onDispose() =>
      (super.noSuchMethod(Invocation.method(#onDispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PersistedSolevatoConversationDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistedSolevatoConversationDao extends _i1.Mock
    implements _i2.PersistedSolevatoConversationDao {
  MockPersistedSolevatoConversationDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> deleteConversation() =>
      (super.noSuchMethod(Invocation.method(#deleteConversation, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> saveConversation(_i4.SolevatoConversation? conversation) =>
      (super.noSuchMethod(Invocation.method(#saveConversation, [conversation]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> onDispose() =>
      (super.noSuchMethod(Invocation.method(#onDispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PersistedSolevatoContactDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistedSolevatoContactDao extends _i1.Mock
    implements _i5.PersistedSolevatoContactDao {
  MockPersistedSolevatoContactDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> deleteContact() =>
      (super.noSuchMethod(Invocation.method(#deleteContact, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> saveContact(_i6.SolevatoContact? contact) =>
      (super.noSuchMethod(Invocation.method(#saveContact, [contact]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> onDispose() =>
      (super.noSuchMethod(Invocation.method(#onDispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PersistedSolevatoMessagesDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistedSolevatoMessagesDao extends _i1.Mock
    implements _i7.PersistedSolevatoMessagesDao {
  MockPersistedSolevatoMessagesDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> clear() => (super.noSuchMethod(Invocation.method(#clear, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> saveMessage(_i8.SolevatoMessage? message) =>
      (super.noSuchMethod(Invocation.method(#saveMessage, [message]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> saveAllMessages(List<_i8.SolevatoMessage>? messages) =>
      (super.noSuchMethod(Invocation.method(#saveAllMessages, [messages]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  List<_i8.SolevatoMessage> getMessages() =>
      (super.noSuchMethod(Invocation.method(#getMessages, []),
          returnValue: <_i8.SolevatoMessage>[]) as List<_i8.SolevatoMessage>);
  @override
  _i3.Future<void> onDispose() =>
      (super.noSuchMethod(Invocation.method(#onDispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteMessage(int? messageId) =>
      (super.noSuchMethod(Invocation.method(#deleteMessage, [messageId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i8.SolevatoMessage? getMessage(int? messageId) =>
      (super.noSuchMethod(Invocation.method(#getMessage, [messageId]))
          as _i8.SolevatoMessage?);
  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SolevatoUserDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSolevatoUserDao extends _i1.Mock implements _i9.SolevatoUserDao {
  MockSolevatoUserDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveUser(_i10.SolevatoUser? user) =>
      (super.noSuchMethod(Invocation.method(#saveUser, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteUser() =>
      (super.noSuchMethod(Invocation.method(#deleteUser, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> onDispose() =>
      (super.noSuchMethod(Invocation.method(#onDispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PersistedSolevatoUserDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistedSolevatoUserDao extends _i1.Mock
    implements _i9.PersistedSolevatoUserDao {
  MockPersistedSolevatoUserDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> deleteUser() =>
      (super.noSuchMethod(Invocation.method(#deleteUser, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> saveUser(_i10.SolevatoUser? user) =>
      (super.noSuchMethod(Invocation.method(#saveUser, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> onDispose() =>
      (super.noSuchMethod(Invocation.method(#onDispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
